### ISSUE TITLE
Assembly signing

### ISSUE THREAD

**Issue by igatanasov** [SamuelEnglard/System.AppDomain#1]
Could you sign the assembly so it can be used in signed projects?

**Comment by SamuelEnglard** [comment]
Just uploaded to NuGet a new version that is signed. I'll leave this open till it's indexed.

**Comment by igatanasov** [comment]
Hi @SamuelEnglard 

I'm not able to install and use the nuget package since the culture is specific:

System.AppDomain, Version=2.0.0.0, Culture=en-US

but in the previous version is:
System.AppDomain, Version=1.1.1.0, Culture=neutral

Can you rollback the culture and I will give it a try again?

**Comment by SamuelEnglard** [comment]
Sorry about that, just uploaded new package with culture reset to neutral

**Comment by igatanasov** [comment]
No worries I will try it tomorrow

**Comment by igatanasov** [comment]
Hi @SamuelEnglard 

I have just tested the implementation and nuget package version 2.0.1 and works.
