### ISSUE TITLE
CS3001: Argument type 'AppDomain' is not CLS-compliany

### ISSUE THREAD

**Issue by niemyjski** [SamuelEnglard/System.AppDomain#2]
I'm getting the error above, has anyone found a work around for this? I haven't investigated it any, wonder if we are just missing the cls attribute.

**Comment by SamuelEnglard** [comment]
You'd get that error if your library is marked CLS compliant and exposes AppDomain which I haven't (but probably should) mark as CLS compliant. Why do you need to expose AppDomain?

**Comment by niemyjski** [comment]
Our public api exposes it so a user can pass in an app domain to register up error handlers (useful when you use multiple domains in a single app)

https://github.com/exceptionless/Exceptionless.Net/search?utf8=%E2%9C%93&q=appdomain

**Comment by niemyjski** [comment]
Is there any chance we could get a new release with this out there. I'm getting a compiler error upgrading this and I'm getting really close to getting it all working.

**Comment by SamuelEnglard** [comment]
Good enough reason

**Comment by SamuelEnglard** [comment]
Published https://www.nuget.org/packages/System.AppDomain/2.0.5

**Comment by niemyjski** [comment]
Thanks!
