### ISSUE TITLE
Please create a poly fill for AppDomain.CurrentDomain.GetAssemblies()

### ISSUE THREAD

**Issue by niemyjski** [SamuelEnglard/System.AppDomain#3]
I need a poly fill for AppDomain.CurrentDomain.GetAssemblies() even if it returns an empty enumerable. On .net core apps there is an existing package that will fill this in but it doesn't make sense to have that and it doesn't work on net standard.

**Comment by SamuelEnglard** [comment]
What's the pollyfil?

**Comment by niemyjski** [comment]
https://github.com/StefH/System.AppDomain.Core/blob/master/src/System.AppDomain.NetCoreApp/AppDomain.cs

or even if you returned an empty array..

**Comment by SamuelEnglard** [comment]
If I can't get the assemblies from the internal AppDomain I'll use that polyfill (and give credit of course!)

**Comment by niemyjski** [comment]
Thanks, looks like were also missing `AppDomain.CurrentDomain.FriendlyName` which is just the name of the app domain (could return null here)

**Comment by niemyjski** [comment]
As well as `GetData` which returns an object.

```
AppDomain.CurrentDomain.GetData("DataDirectory") 
```

**Comment by SamuelEnglard** [comment]
Those I think are there

**Comment by niemyjski** [comment]
I'm getting compile time errors for them

**Comment by SamuelEnglard** [comment]
I meant in the hidden AppDomain

**Comment by SamuelEnglard** [comment]
Decided I'm going to give the surface area of 4.6 `AppDomain` with some members just doing nothing really

**Comment by SamuelEnglard** [comment]
Ok good news, the internal AppDomain has GetAssemblies so I can just call that!

**Comment by niemyjski** [comment]
Awesome!

**Comment by SamuelEnglard** [comment]
Done, committed, and submitted to NuGet!

**Comment by niemyjski** [comment]
Thanks!

Any chance we could get support for `AppDomain.CurrentDomain.GetData("DataDirectory") ` and `AppDomain.CurrentDomain.FriendlyName`

![screen shot 2016-05-31 at 8 43 26 pm](https://cloud.githubusercontent.com/assets/1020579/15695778/5c29325a-2770-11e6-9915-2dda9ca5ab08.png)

**Comment by niemyjski** [comment]
Thanks!
