### ISSUE TITLE
Add AppDomain.DomainManager

### ISSUE THREAD

**Issue by qmfrederik** [SamuelEnglard/System.AppDomain#4]
Hi,

Would be great if you could add the [AppDomain.DomainManager](https://technet.microsoft.com/nl-be/library/system.appdomain.domainmanager) property. For my use case, you can stub the DomainManager class and just return null, but I'm porting some code which expects the property to exist :-).

Thanks!

**Comment by SamuelEnglard** [comment]
The class is actually there (hidden of course) so I'll exposes it. Will take some time to get it all wrapped up.

**Comment by SamuelEnglard** [comment]
Just wanted to update that I've begun work on this

**Comment by qmfrederik** [comment]
Cool, looking forward to it!

**Comment by SamuelEnglard** [comment]
So many classes in that chain!

**Comment by qmfrederik** [comment]
I think this has been solved by .NET Core 2.0 ;)
