### ISSUE TITLE
Add polyfill for get_SetupInformation()

### ISSUE THREAD

**Issue by gmetzger** [SamuelEnglard/System.AppDomain#9]
Is it possible to add code to handle this Error Message: Method not found: 'System.AppDomainSetup System.AppDomain.get_SetupInformation()'.

**Comment by SamuelEnglard** [comment]
What throws the error?

**Comment by gmetzger** [comment]
It was an issue with Spire docx generator - Spire does not support .NET Core, so you can ignore my question. Thanks.
